// Light theme colors
export const lightColors = {
    background: '#ffffff',
    backgroundShaded: '#bbbbbb',
    primary: '#005DAC',
    pLight: '#99bedd',
    statusBar: '#002e45',
    navBar: '#002e45',
    formBackground: '#ddd',
    formText: '#555',
    buttonBackground: '#E97E33',
    buttonText: '#fff',
    footerNav: '#002e45',
    footerButtonBackground: '#1E6EB4',
    footerButtonText: '#fff',
    text: '#000000',
    accent: '#E97E33',
    error: '#EF9A9A',
    notificationBackground: '#AAD1DE',
    notificationText: '#38474F',
  };
  
// Dark theme colors
export const darkColors = {
    background: '#3F4253',
    backgroundShaded: '#1F2233',
    primary: '#005DAC',
    pLight: '#3F4253',
    statusBar: '#171921',
    navBar: '#171921',
    formBackground: '#ddd',
    formText: '#555',
    buttonBackground: '#E97E33',
    buttonText: '#fff',
    footerNav: '#171921',
    footerButtonBackground: '#1E6EB4',
    footerButtonText: '#fff',
    text: '#FFFFFF',
    accent: '#E97E33',
    error: '#EF9A9A',
    notificationBackground: '#AAD1DE',
    notificationText: '#38474F',
};